/*
 * This source file was generated by the Gradle 'init' task
 */
package ticket.booking;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.function.Predicate;
import java.util.stream.Collectors;

public class App {

    public static void main(String[] args) {

    }
}
